site_name: LightGraphs.jl
site_author: Seth Bromberger, James Fairbanks, Carlo Lucibello
repo_url: https://github.com/JuliaGraphs/LightGraphs.jl/
docs_dir: 'build'

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

pages:
  - 'Getting Started': 'index.md'
  - 'Networks': 'netowork.md'
  - 'Nets': 'net.md'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
